version: "3.8"

services:
  web:
    image: huldcz/aiscr_prod:latest
    container_name: web
    secrets:
      - db_conf
    volumes:
      - static_data:/vol/web
      - locale_data:/vol/web/locale
      - nginx_data:/vol/web/nginx/data
    networks:
      - aiscr-webamcr_reverse-proxy
    ports:
      - "8000:8000"

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - aiscr-webamcr_reverse-proxy

volumes:
  static_data:
  locale_data:
  nginx_data:


networks:
  aiscr-webamcr_reverse-proxy:
    external: true

secrets:
  db_conf:
   external : true