version: "3.8"

services:
  web:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webclient:/code
      # - C:/tmp_media:/vol/web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=webclient.settings.dev
