name: Django Tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      postgres: # we need a postgres docker image to be booted a side car service to run the tests that needs a db
        image: postgis/postgis
        env: # the environment variable must match with app/settings.py if block of DATBASES variable otherwise test will fail due to connectivity issue.
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_secretpass
          POSTGRES_DB: test_db_2
        ports:
          - 5432:5432 # exposing 5432 port for application to use
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s  --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r webclient/webclient/requirements/dev.txt
    - name: Install gdal dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev locales
        gdal-config --version
      env:
        CPLUS_INCLUDE_PATH: /usr/include/gdal
        C_INCLUDE_PATH: /usr/include/gdal
    - name: Install gdal
      run: |
        pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
    - name: Run Collect Static and Migrations for heslar
      working-directory: ./webclient
      run: |
        sudo mkdir -p /vol/web/media
        sudo mkdir -p /vol/web/static
        sudo chmod -R 777 /vol/web
        python manage.py collectstatic --settings=webclient.settings.github_ci
        python manage.py migrate heslar --skip-checks --settings=webclient.settings.github_ci
    - name: Run Migrations for auth
      working-directory: ./webclient
      run: |
        sudo mkdir -p /vol/web/media
        sudo chmod -R 777 /vol/web
        python manage.py migrate auth --settings=webclient.settings.github_ci
    - name: Run Migrations
      working-directory: ./webclient
      run: |
        python manage.py migrate --settings=webclient.settings.github_ci
    - name: Django Testing
      working-directory: ./webclient
      run: |
        python manage.py test --settings=webclient.settings.github_ci
      env:
        REDIS_URL: "localhost:6379"
