name: Django Tests

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres: # we need a postgres docker image to be booted a side car service to run the tests that needs a db
        image: postgis/postgis
        env: # the environment variable must match with app/settings.py if block of DATBASES variable otherwise test will fail due to connectivity issue.
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_secretpass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432 # exposing 5432 port for application to use
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r webclient/webclient/requirements/dev.txt
    - name: Install gdal
      run: |
        pip install GDAL==3.0.4
    - name: Coverage report
      working-directory: ./webclient
      run: |
        coverage run manage.py test --settings=webclient.settings.local_test
        coverage report
    - name: Django Testing
      working-directory: ./webclient
      run: |
        python3 manage.py test
