name: Publish Docker images

# on:
#   release:
#     types: [published]

on:
  create:
    tags:
      - "v**"

env:
  DOCKER_HUB_REPO_DEV: huldcz/aiscr_dev
  DOCKER_HUB_REPO_PROXY: huldcz/aiscr_proxy
  DOCKER_HUB_REPO_PROD: huldcz/aiscr_prod
  DOCKER_HUB_USERNAME: huldcz
  # @IMPORTANT: when Github secrets settings for repository will be accessible (i.e. permission granted by maintainer) this shall be IMMEDIATELY replaced!
  DOCKER_HUB_ACCESS_TOKEN: dckr_pat_fpWRR1MNMpRZiycqTtFc2bEJh2Q

jobs:
  push_development:
    name: Build and push docker images for production/testing to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for docker dev image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_REPO_DEV }}

      - name: Get tag from GITHUB_REF
        id: step_tag1
        run: echo "tag_version=$(echo $GITHUB_REF | cut -d/ -f3)" >> $GITHUB_ENV

      #---------------------
      # BUILD DEV
      #---------------------
      # - name: DEV - Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: Dockerfile-DEV
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     build-args: |
      #       VERSION_APP=${{ env.tag_version }}
      #       TAG_APP=${{ github.ref }}
      # #---------------------
      # BUILD PROD
      #---------------------
      - name: Extract metadata (tags, labels) for Docker production image
        id: meta_prod
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_REPO_PROD }}

      - name: PRODUCTION - Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-production
          push: true
          tags: ${{ steps.meta_prod.outputs.tags }}
          labels: ${{ steps.meta_prod.outputs.labels }}
          build-args: |
            VERSION_APP=${{ env.tag_version }}
            TAG_APP=${{ github.ref }}
              - name: Build and push Docker image
      #---------------------
      # BUILD PROXY
      #---------------------
      - name: Extract metadata (tags, labels) for Docker proxy image
        id: meta_proxy
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_REPO_PROXY }}

      - name: PROXY - Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./proxy
          push: true
          tags: ${{ steps.meta_proxy.outputs.tags }}
          labels: ${{ steps.meta_proxy.outputs.labels }}
          build-args: |
            VERSION_APP=${{ env.tag_version }}
            TAG_APP=${{ github.ref }}
